import smtplib
from email.mime.text import MIMEText
title="Vedicfolks"
b='Kamala Devi Mahavidya Maha Homam'
c='Crucial Dasa Mahavidya For Material Well Being With Kundalini Awakening (Tantra)'
"""
msg_content='<p style="text-align: center;"><span style="font-size: 14pt; color: #800080;"><strong><span style="font-family: verdana,geneva,sans-serif;">Vedicfolks Signature Rituals Of 2017</span> </strong></span><br /><span style="color: #ff6600;"><strong><span style="font-size: 24pt; font-family: times new roman,times,serif;">Kamala Devi Mahavidya Maha Homam</span></strong></span><br /><span style="color: #800000;"><strong><span style="font-family: verdana,geneva,sans-serif; font-size: 12pt;">Last &amp; "Crucial Dasa Mahavidya For Material Well Being With Kundalini Awakening (Tantra)"</span></strong></span></p>'
msg_1content='<p style="text-align: justify;"><span style="font-size: 14pt; font-family: times new roman,times,serif; color: #000000;">"Goddess Kamala Devi as the name denotes, She is the goddess of lotus and last among the dasmahavidya. She&rsquo;s the purest of all Mahavidya and also is a form of Goddess Lakshmi. She bestows devotees with prosperity, fertility, abundance in all types of wealth. She also strengthens Planet Venus in order to remove the malefic nature of the planet. Goddess Kamala Devi provides nourishment and support for all life activities too. We at Vedicfolks is going to organize Goddess Kamala Devi Homam which helps to seek enormous benefits and also our special rituals with this homam enhance the power of goddess and invokes the Suktha Amirtha Chakra &amp; grants the material benefits from all the ten Mahavidya.&nbsp;"</span></p>'
msg_3content='<img src="http://www.vedicfolks.com/serviceimg/banner/banner_1512467992.jpg" alt="Mountain View">'
msg_4content='<p style="text-align: center;"><span style="font-family: arial,helvetica,sans-serif; color: #ff6600; font-size: 18pt;"><strong>"Goddess Kamala Devi Homam and Powerful Ceremonies"</strong></span></p>'
msg_5content='<p style="text-align: center;"><span style="font-family: arial,helvetica,sans-serif; color: #008000; font-size: 14pt;"><strong>"Scheduled&nbsp;LIVE on "<span class="aBn" tabindex="0" data-term="goog_82724579"><span class="aQJ">"December 15, 2017 @ 6 PM IST"</span></span></strong></span></p>'
msg_6content='<p><span style="font-size: 14pt; font-family:times new roman,times,serif;"><span style="color: #800000; font-family: verdana,geneva,sans-serif; font-size: 12pt;"><strong>"Kamala Devi Homam"</strong> </span>&ndash; <span style="color: #000000;">"Kamala Devi homam fetches spiritual and material blessings from the divine deity who is equal to goddess Lakshmi. she also gratns fortune, power, fertility and abundance in everything."</span> <br /></span></p>'
msg_7content='<p><span style="color: #800000; font-family: verdana,geneva,sans-serif; font-size: 12pt;"><strong>"Ardha Nareeshwarar Puja"</strong></span><span style="font-family:times new roman,times,serif; font-size: 14pt; color: #000000;"> "A Puja to Lord Ardha Nareeshwara removes all mangalya dosha, clears domestic conflicts and enriches family ties."</span></p>'
msg_8content='<p><span style="font-size: 14pt; font-family:times new roman,times,serif;"><span style="color: #800000; font-family: verdana,geneva,sans-serif; font-size: 12pt;"><strong>"Amrutheshwari Puja"</strong></span> - <span style="color: #000000;">"A puja to Goddess Amrutheshwari bestows one with blessings of progeny, salvation and material prosperity."</span> <br /></span></p>'
msg_9content='<p><span style="font-size: 14pt; font-family:times new roman,times,serif;"><span style="color: #800000; font-family: verdana,geneva,sans-serif; font-size: 12pt;"><strong>"Energised Suktha Amirtha Yantra&nbsp;"</strong></span>&ndash;<span style="color: #000000;">"A puja to this yantra invokes the powers of Goddess Amrutheshwari, the goddess of the Suktha Amritha Yantra. get relief from incurable diseases, blessings of prosperity and good progeny."</span> <br /></span></p>'
msg_10content='<p><span style="font-size: 14pt; font-family:times new roman,times,serif;"><span style="color: #800000; font-family: verdana,geneva,sans-serif; font-size: 12pt;"><strong>"Kamalambigai Temple Puja"</strong></span> &ndash; <span style="color: #000000;">"A puja in this famous temple gets you the blessings of strength and courage, overcomes financial crisis, cures illnesses, fulfills all matrimonial matters and ensures excellence in arts."</span> <br /></span></p>'
msg_11content='p><span style="font-size: 14pt; font-family:times new roman,times,serif;"><span style="color: #800000; font-family: verdana,geneva,sans-serif; font-size: 12pt;"><strong>"Energised Lotus Coin"</strong> </span>&ndash; <span style="color: #000000;">"This powerful product brings prosperity and fortune to your space and one can also carry it along for good luck."</span></span></p><p>&nbsp;</p>'
msg_12content='<div <p><span style="font-family: times new roman,times,serif; font-size: 14pt;">"Thanks &amp; Regards,"</span></p><p><span style="font-family: helvetica,arial,sans-serif; font-size: 12pt;">"Sharmiladevi. A,"</span><em> "Customer Support &nbsp; &nbsp; &nbsp; &nbsp;"</em></p><p><span style="color: #000000;"><em>&nbsp;<img src="https://pbs.twimg.com/profile_images/479870783297032195/SryHQVtj_400x400.png" style="width: 24px; height: 24px; max-width: 100%; float: left;" alt="" width="24" height="24" /></em></span><a href="http://www.vedicfolks.com/">"www.vedicfolks.com"</a><span style="color: #000000;">&nbsp;"+91 7338766066"</span></p></div>'
msg=msg_content+msg_1content+msg_3content+msg_4content+msg_5content+msg_6content+msg_7content+msg_8content+msg_9content+msg_10content+msg_11content+msg_12content
"""
title = 'Naveen'
msg_00content = '<p><span style="font-size: 18pt;font-family: arial,helvetica,sans-serif; ">Namaste {title},</p>'.format(title=title)
msg_content='<p style="text-align: center;"><span style="font-size: 14pt; color: #800080;"><strong><span style="font-family: verdana,geneva,sans-serif;">Vedicfolks Signature Rituals Of 2017</span> </strong></span><br /><span style="color: #ff6600;"><strong><span style="font-size: 24pt; font-family: times new roman,times,serif;">Kamala Devi Mahavidya Maha Homam</span></strong></span><br /><span style="color: #800000;"><strong><span style="font-family: verdana,geneva,sans-serif; font-size: 12pt;">Last &amp; Crucial Dasa Mahavidya For Material Well Being With Kundalini Awakening (Tantra)</span></strong></span></p>'
msg_1content='<p style="text-align: justify;"><span style="font-size: 14pt; font-family: times new roman,times,serif; color: #000000;">Goddess Kamala Devi as the name denotes, She is the goddess of lotus and last among the dasmahavidya. She&rsquo;s the purest of all Mahavidya and also is a form of Goddess Lakshmi. She bestows devotees with prosperity, fertility, abundance in all types of wealth. She also strengthens Planet Venus in order to remove the malefic nature of the planet. Goddess Kamala Devi provides nourishment and support for all life activities too. We at Vedicfolks is going to organize Goddess Kamala Devi Homam which helps to seek enormous benefits and also our special rituals with this homam enhance the power of goddess and invokes the Suktha Amirtha Chakra &amp; grants the material benefits from all the ten Mahavidya.&nbsp;</span></p>'
msg_3content='<img src="http://www.vedicfolks.com/serviceimg/banner/banner_1512467992.jpg" alt="Mountain View">'
msg_4content='<p style="text-align: center;"><span style="font-family: arial,helvetica,sans-serif; color: #ff6600; font-size: 18pt;"><strong>Goddess Kamala Devi Homam and Powerful Ceremonies</strong></span></p>'
msg_5content='<p style="text-align: center;"><span style="font-family: arial,helvetica,sans-serif; color: #008000; font-size: 14pt;"><strong>"Scheduled&nbsp;LIVE on "<span class="aBn" tabindex="0" data-term="goog_82724579"><span class="aQJ">December 15, 2017 @ 6 PM IST</span></span></strong></span></p>'
msg_6content='<p><span style="font-size: 14pt; font-family:times new roman,times,serif;"><span style="color: #800000; font-family: verdana,geneva,sans-serif; font-size: 12pt;"><strong>Kamala Devi Homam</strong> </span>&ndash; <span style="color: #000000;">Kamala Devi homam fetches spiritual and material blessings from the divine deity who is equal to goddess Lakshmi. she also gratns fortune, power, fertility and abundance in everything.</span> <br /></span></p>'
msg_7content='<p><span style="color: #800000; font-family: verdana,geneva,sans-serif; font-size: 12pt;"><strong>Ardha Nareeshwarar Puja</strong></span><span style="font-family:times new roman,times,serif; font-size: 14pt; color: #000000;"> A Puja to Lord Ardha Nareeshwara removes all mangalya dosha, clears domestic conflicts and enriches family ties.</span></p>'
msg_8content='<p><span style="font-size: 14pt; font-family:times new roman,times,serif;"><span style="color: #800000; font-family: verdana,geneva,sans-serif; font-size: 12pt;"><strong>Amrutheshwari Puja</strong></span> - <span style="color: #000000;">A puja to Goddess Amrutheshwari bestows one with blessings of progeny, salvation and material prosperity.</span> <br /></span></p>'
msg_9content='<p><span style="font-size: 14pt; font-family:times new roman,times,serif;"><span style="color: #800000; font-family: verdana,geneva,sans-serif; font-size: 12pt;"><strong>Energised Suktha Amirtha Yantra&nbsp;</strong></span>&ndash;<span style="color: #000000;">A puja to this yantra invokes the powers of Goddess Amrutheshwari, the goddess of the Suktha Amritha Yantra. get relief from incurable diseases, blessings of prosperity and good progeny.</span> <br /></span></p>'
msg_10content='<p><span style="font-size: 14pt; font-family:times new roman,times,serif;"><span style="color: #800000; font-family: verdana,geneva,sans-serif; font-size: 12pt;"><strong>Kamalambigai Temple Puja</strong></span> &ndash; <span style="color: #000000;">A puja in this famous temple gets you the blessings of strength and courage, overcomes financial crisis, cures illnesses, fulfills all matrimonial matters and ensures excellence in arts.</span> <br /></span></p>'
msg_11content='<p><span style="font-size: 14pt; font-family:times new roman,times,serif;"><span style="color: #800000; font-family: verdana,geneva,sans-serif; font-size: 12pt;"><strong>Energised Lotus Coin</strong> </span>&ndash; <span style="color: #000000;">This powerful product brings prosperity and fortune to your space and one can also carry it along for good luck.</span></span></p><p>&nbsp;</p>'
msg_12content='<div <p><span style="font-family: times new roman,times,serif; font-size: 14pt;">Thanks &amp; Regards,</span></p><p><span style="font-family: helvetica,arial,sans-serif; font-size: 12pt;">Sharmiladevi. A,</span><em> Customer Support &nbsp; &nbsp; &nbsp; &nbsp;</em></p><p><span style="color: #000000;"><em>&nbsp;<img src="https://pbs.twimg.com/profile_images/479870783297032195/SryHQVtj_400x400.png" style="width: 24px; height: 24px; max-width: 100%; float: left;" alt="" width="24" height="24" /></em></span><a href="http://www.vedicfolks.com/">www.vedicfolks.com</a><span style="color: #000000;">&nbsp;+91 7338766066</span></p></div>'
msg_13content='<p><span style="font-family: times new roman,times,serif; font-size: 14pt; color: #ff0000;"><strong>Book Now! </strong><span style="color: #000000;">To Participate and&nbsp;Acquire Blessing of Fertility, Growth, Royal Grandeur &amp; Eradicate Augury From Life</span></span></p><p><a href="http://www.vedicfolks.com/life-time-management/karma-remedies/shared-homam/kamala-devi-mahavidya-homam.html" target="_blank">life-time-management/karma-<wbr />remedies/shared-homam/kamala-<wbr />devi-mahavidya-homam.html</a></p>'
msg=msg_00content+msg_content+msg_1content+msg_3content+msg_4content+msg_5content+msg_6content+msg_7content+msg_8content+msg_9content+msg_10content+msg_11content+msg_13content+msg_12content
message = MIMEText(msg, 'html')
message['From'] = 'Sender Name <naveeniyantras@gmail.com>'
message['To'] = 'Receiver Name <naveeniyantras@gmail.com>'
#message['Cc'] = 'Receiver2 Name <receiver2@server>'
message['Subject'] = 'Automation Test- Last Call : Vedicfolks Signature Rituals 2017 Kamala Devi Mahavidya Homam For Material Well Being With Kundalini Awakening (Tantra)'
msg_full = message.as_string()
server = smtplib.SMTP('smtp.gmail.com:587')
server.starttls()
server.login('naveeniyantras@gmail.com', 'naveeniyantras')
server.sendmail('naveeniyantras@gmail.com',
                ['naveeniyantras@gmail.com', 'naveeniyantras@gmail.com'],
                msg_full)
print(" \n Sent!")
server.quit()